/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "alerts": {
        "language_already_exists": string;
        "success_created": string;
    };
    "buttons": {
        "back": string;
        "change_language": string;
        "faq": string;
        "name": string;
        "accept": string;
        "cancel": string;
        "delete_photo": string;
        "admin": {
            "home": string;
            "create": string;
            "control": string;
        };
        "buy": string;
    };
    "phrases": {
        "home": string;
        "change_language": string;
        "faq": string;
        "admin": string;
        "error": string;
        "if_you_want_image": string;
        "statuses": {
            "creation": string;
            "pending-enter": string;
        };
        "templates": {
            "item-value": string;
            "item-values-2": string;
        };
        "objects": {
            "name": string;
            "description": string;
        };
    };
    "languages": {
        "en": string;
        "ru": string;
    };
    "forward": string;
    "backward": string;
    "scenes": {
        "home": string;
        "faq": string;
        "admin": string;
        "change_language": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
